spring:
    application:
        name: movie-land

    datasource:
        url: ${SPRING_DATASOURCE_URL}
        username: ${SPRING_DATASOURCE_USERNAME}
        password: ${SPRING_DATASOURCE_PASSWORD}
        driver-class-name: ${SPRING_DATASOURCE_DRIVER_CLASS_NAME:org.postgresql.Driver}

    jpa:
        show-sql: true
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
                format_sql: true
                javax:
                    cache:
                        provider: org.ehcache.jsr107.EhcacheCachingProvider
                        uri: classpath:ehcache.xml

    flyway:
        enabled: true
        validate-on-migrate: true
        locations: classpath:db/migration

server:
    port: ${PORT:8080}

cache:
    rate:
        refresh-cron: "0 30 15 * * *" #every day 15:30

client:
    rate:
        url: ${CLIENT_RATE_URL}



concurrent:
    enrichment:
        timeout: 5

logging:
    config: classpath:logback-spring.xml

security:
    jwt:
        secret: ${SECURITY_JWT_SECRET:his-is-a-very-long-secret-key-that-is-at-least-256-bits-long-for-hmac-sha256}
        ttl-seconds: ${SECURITY_JWT_TTL:900} #15 min
        blacklist:
            cleanup-cron: "0 * * * * *" # every minute