spring:
    application:
        name: movie-land

    datasource:
        url: ${SPRING_DATASOURCE_URL}
        username: ${SPRING_DATASOURCE_USERNAME}
        password: ${SPRING_DATASOURCE_PASSWORD}
        driver-class-name: ${SPRING_DATASOURCE_DRIVER_CLASS_NAME:org.postgresql.Driver}

    jpa:
#        show-sql: true
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
                format_sql: true

    flyway:
        enabled: true
        validate-on-migrate: true

server:
    port: ${PORT:8080}

logging:
    config: classpath:logback-spring.xml


cache:
    genre:
        refresh-interval: 4h
    rate:
        refresh-cron: "0 0 0 * * *"

session:
    ttl: 120m
    cleanup-interval: 5m

client:
    rate:
        url: ${CLIENT_RATE_URL}

movie:
    enrichment:
        timeout-seconds: 25